.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. fargocoin_qt test_fargocoin_qt
clean: FORCE
	$(MAKE) -C .. fargocoin_qt_clean test_fargocoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_fargocoin_qt_check
fargocoin-qt fargocoin-qt.exe: FORCE
	 $(MAKE) -C .. fargocoin_qt
